assets:
  SPX:
    symbol: SPX
    cex_symbol: SPXUSDT
    order_size: 159.6
    max_inventory: 319.1
    base_spread: 0.01
    risk_aversion: 2.0
    inventory_aversion: 0.5
    volatility_lookback: 60
    max_volatility: 0.1
    min_quote_interval_ms: 50
    reduce_only_ratio: 0.95
    tick_size: 1.0e-05
    quote_reprice_tolerance_ticks: 2.0
    vol_spread_multiplier: 5.0
  LINK:
    symbol: LINK
    cex_symbol: LINKUSDT
    order_size: 7.1
    max_inventory: 14.2
    base_spread: 0.01
    risk_aversion: 2.0
    inventory_aversion: 0.5
    volatility_lookback: 60
    max_volatility: 0.1
    min_quote_interval_ms: 50
    reduce_only_ratio: 0.95
    tick_size: 0.001
    quote_reprice_tolerance_ticks: 2.0
    vol_spread_multiplier: 5.0
  kLUNC:
    symbol: kLUNC
    cex_symbol: kLUNCUSDT
    order_size: 2189
    max_inventory: 4378
    base_spread: 0.01
    risk_aversion: 2.0
    inventory_aversion: 0.5
    volatility_lookback: 60
    max_volatility: 0.1
    min_quote_interval_ms: 50
    reduce_only_ratio: 0.95
    tick_size: 1.0e-06
    quote_reprice_tolerance_ticks: 2.0
    vol_spread_multiplier: 5.0
  STABLE:
    symbol: STABLE
    cex_symbol: STABLEUSDT
    order_size: 7241
    max_inventory: 14482
    base_spread: 0.01
    risk_aversion: 2.0
    inventory_aversion: 0.5
    volatility_lookback: 60
    max_volatility: 0.1
    min_quote_interval_ms: 50
    reduce_only_ratio: 0.95
    tick_size: 1.0e-06
    quote_reprice_tolerance_ticks: 2.0
    vol_spread_multiplier: 5.0
  kPEPE:
    symbol: kPEPE
    cex_symbol: kPEPEUSDT
    order_size: 21819
    max_inventory: 43639
    base_spread: 0.01
    risk_aversion: 2.0
    inventory_aversion: 0.5
    volatility_lookback: 60
    max_volatility: 0.1
    min_quote_interval_ms: 50
    reduce_only_ratio: 0.95
    tick_size: 1.0e-06
    quote_reprice_tolerance_ticks: 2.0
    vol_spread_multiplier: 5.0
  WLD:
    symbol: WLD
    cex_symbol: WLDUSDT
    order_size: 166.0
    max_inventory: 331.9
    base_spread: 0.01
    risk_aversion: 2.0
    inventory_aversion: 0.5
    volatility_lookback: 60
    max_volatility: 0.1
    min_quote_interval_ms: 50
    reduce_only_ratio: 0.95
    tick_size: 1.0e-05
    quote_reprice_tolerance_ticks: 2.0
    vol_spread_multiplier: 5.0
  kBONK:
    symbol: kBONK
    cex_symbol: kBONKUSDT
    order_size: 10411
    max_inventory: 20822
    base_spread: 0.01
    risk_aversion: 2.0
    inventory_aversion: 0.5
    volatility_lookback: 60
    max_volatility: 0.1
    min_quote_interval_ms: 50
    reduce_only_ratio: 0.95
    tick_size: 1.0e-06
    quote_reprice_tolerance_ticks: 2.0
    vol_spread_multiplier: 5.0
  ARB:
    symbol: ARB
    cex_symbol: ARBUSDT
    order_size: 465.3
    max_inventory: 930.7
    base_spread: 0.01
    risk_aversion: 2.0
    inventory_aversion: 0.5
    volatility_lookback: 60
    max_volatility: 0.1
    min_quote_interval_ms: 50
    reduce_only_ratio: 0.95
    tick_size: 1.0e-05
    quote_reprice_tolerance_ticks: 2.0
    vol_spread_multiplier: 5.0
  BCH:
    symbol: BCH
    cex_symbol: BCHUSDT
    order_size: 0.173
    max_inventory: 0.345
    base_spread: 0.01
    risk_aversion: 2.0
    inventory_aversion: 0.5
    volatility_lookback: 60
    max_volatility: 0.1
    min_quote_interval_ms: 50
    reduce_only_ratio: 0.95
    tick_size: 0.01
    quote_reprice_tolerance_ticks: 2.0
    vol_spread_multiplier: 5.0
  LTC:
    symbol: LTC
    cex_symbol: LTCUSDT
    order_size: 1.2
    max_inventory: 2.4
    base_spread: 0.01
    risk_aversion: 2.0
    inventory_aversion: 0.5
    volatility_lookback: 60
    max_volatility: 0.1
    min_quote_interval_ms: 50
    reduce_only_ratio: 0.95
    tick_size: 0.001
    quote_reprice_tolerance_ticks: 2.0
    vol_spread_multiplier: 5.0
risk:
  tick_interval_ms: 50
  inventory_check_interval: 1.0
  metrics_flush_seconds: 60.0
economics:
  reload_threshold_budget: 500.0
  reload_target_budget: 5000.0
  reload_symbol: BTC
  max_spread_bps: 1000.0
discovery:
  enabled: false
