assets:
  BCH:
    symbol: BCH
    cex_symbol: BCHUSDT
    order_size: 0.174
    max_inventory: 0.349
    base_spread: 0.003
    risk_aversion: 2.0
    inventory_aversion: 0.5
    volatility_lookback: 60
    max_volatility: 0.1
    min_quote_interval_ms: 1000
    reduce_only_ratio: 0.95
    tick_size: 0.01
    quote_reprice_tolerance_ticks: 2.0
    vol_spread_multiplier: 10.0
  WLD:
    symbol: WLD
    cex_symbol: WLDUSDT
    order_size: 166.2
    max_inventory: 332.4
    base_spread: 0.003
    risk_aversion: 2.0
    inventory_aversion: 0.5
    volatility_lookback: 60
    max_volatility: 0.1
    min_quote_interval_ms: 1000
    reduce_only_ratio: 0.95
    tick_size: 1.0e-05
    quote_reprice_tolerance_ticks: 2.0
    vol_spread_multiplier: 10.0
  LTC:
    symbol: LTC
    cex_symbol: LTCUSDT
    order_size: 1.2
    max_inventory: 2.4
    base_spread: 0.003
    risk_aversion: 2.0
    inventory_aversion: 0.5
    volatility_lookback: 60
    max_volatility: 0.1
    min_quote_interval_ms: 1000
    reduce_only_ratio: 0.95
    tick_size: 0.001
    quote_reprice_tolerance_ticks: 2.0
    vol_spread_multiplier: 10.0
  ARB:
    symbol: ARB
    cex_symbol: ARBUSDT
    order_size: 465.7
    max_inventory: 931.4
    base_spread: 0.003
    risk_aversion: 2.0
    inventory_aversion: 0.5
    volatility_lookback: 60
    max_volatility: 0.1
    min_quote_interval_ms: 1000
    reduce_only_ratio: 0.95
    tick_size: 1.0e-05
    quote_reprice_tolerance_ticks: 2.0
    vol_spread_multiplier: 10.0
  WIF:
    symbol: WIF
    cex_symbol: WIFUSDT
    order_size: 242
    max_inventory: 484
    base_spread: 0.003
    risk_aversion: 2.0
    inventory_aversion: 0.5
    volatility_lookback: 60
    max_volatility: 0.1
    min_quote_interval_ms: 1000
    reduce_only_ratio: 0.95
    tick_size: 1.0e-05
    quote_reprice_tolerance_ticks: 2.0
    vol_spread_multiplier: 10.0
  UNI:
    symbol: UNI
    cex_symbol: UNIUSDT
    order_size: 17.9
    max_inventory: 35.8
    base_spread: 0.003
    risk_aversion: 2.0
    inventory_aversion: 0.5
    volatility_lookback: 60
    max_volatility: 0.1
    min_quote_interval_ms: 1000
    reduce_only_ratio: 0.95
    tick_size: 0.0001
    quote_reprice_tolerance_ticks: 2.0
    vol_spread_multiplier: 10.0
  kLUNC:
    symbol: kLUNC
    cex_symbol: kLUNCUSDT
    order_size: 1880
    max_inventory: 3760
    base_spread: 0.003
    risk_aversion: 2.0
    inventory_aversion: 0.5
    volatility_lookback: 60
    max_volatility: 0.1
    min_quote_interval_ms: 1000
    reduce_only_ratio: 0.95
    tick_size: 1.0e-06
    quote_reprice_tolerance_ticks: 2.0
    vol_spread_multiplier: 10.0
  MET:
    symbol: MET
    cex_symbol: METUSDT
    order_size: 370
    max_inventory: 740
    base_spread: 0.003
    risk_aversion: 2.0
    inventory_aversion: 0.5
    volatility_lookback: 60
    max_volatility: 0.1
    min_quote_interval_ms: 1000
    reduce_only_ratio: 0.95
    tick_size: 1.0e-05
    quote_reprice_tolerance_ticks: 2.0
    vol_spread_multiplier: 10.0
  APT:
    symbol: APT
    cex_symbol: APTUSDT
    order_size: 56.96
    max_inventory: 113.93
    base_spread: 0.003
    risk_aversion: 2.0
    inventory_aversion: 0.5
    volatility_lookback: 60
    max_volatility: 0.1
    min_quote_interval_ms: 1000
    reduce_only_ratio: 0.95
    tick_size: 0.0001
    quote_reprice_tolerance_ticks: 2.0
    vol_spread_multiplier: 10.0
  NEAR:
    symbol: NEAR
    cex_symbol: NEARUSDT
    order_size: 58.1
    max_inventory: 116.2
    base_spread: 0.003
    risk_aversion: 2.0
    inventory_aversion: 0.5
    volatility_lookback: 60
    max_volatility: 0.1
    min_quote_interval_ms: 1000
    reduce_only_ratio: 0.95
    tick_size: 0.0001
    quote_reprice_tolerance_ticks: 2.0
    vol_spread_multiplier: 10.0
risk:
  tick_interval_ms: 1000
  inventory_check_interval: 1.0
  metrics_flush_seconds: 60.0
economics:
  reload_threshold_budget: 500.0
  reload_target_budget: 5000.0
  reload_symbol: BTC
  max_spread_bps: 5.0
discovery:
  enabled: false
